query {
  rateLimit {
    limit
    cost
    remaining
    resetAt
  },
  search(
    type: REPOSITORY,
    query: \"

        org:$organization_name

        pushed:$start_date..$end_date

        $github_search_query
    \",
    $cursor_command
    first: 20
  ) {
    repositoryCount
    edges {
      node {
        ... on Repository {
          name
          pushedAt
          createdAt
        }
      }
    },
    pageInfo {
      hasNextPage
      endCursor
    },
  }
  rateLimit {
    limit
    cost
    remaining
    resetAt
  },
}
